language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python main.py
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master
